### PR TITLE
[Custom Elements] Polyfill define lazy2

### PR DESCRIPTION
**Pull request by azakus**
Port of https://github.com/webcomponents/custom-elements/pull/206

### CODE REVIEW

**Comment by azakus** [comment]
@bicknellr looks like some of your edits have the wrong email address

**Comment by bicknellr** [comment]
It looks like GitHub's "auto-commit this recommended change" feature decided to use my personal email when generating the commit messages.

**Comment by bicknellr** [comment]
For @googlebot: I'm a Google employee.

**Comment by bicknellr** [comment]
Moving to #167

**Pull request closed without merging**
